CREATE DATABASE PROYECTO;
USE PROYECTO;
GRANT ALL PRIVILEGES ON PROYECTO.* TO 'RR1998'@'%';

CREATE TABLE PERSONA(
  IDPersona INT NOT NULL AUTO_INCREMENT,
  Nombres VARCHAR(50) NOT NULL,
  Apellidos VARCHAR(50) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  DUI CHAR(10) NOT NULL, ##puede sevir como un ID individual para cada persona
  NIT CHAR(18) NOT NULL,
  Telefono CHAR(8) NULL,
  UNIQUE(Telefono),
  UNIQUE(IDPersona)
);

CREATE TABLE USUARIO(
  IDUsuario INT NOT NULL AUTO_INCREMENT,
  IDPersona INT NOT NULL,
  Usuario VARCHAR(8) NOT NULL,
  Password VARCHAR(15) NOT NULL,
  UNIQUE(Usuario),
  UNIQUE(IDUsuario)
);

#Direccion es mas puntual, solo se usara para poder referise a los lugares especificos como una calle, colonia o lugar de la sucursal
CREATE TABLE SUCURSAL(
  IDSucursal INT NOT NULL AUTO_INCREMENT,
  IDMunicipio INT NOT NULL,
  Telefono CHAR(8) NOT NULL,
  Direccion VARCHAR(50),
  UNIQUE(Telefono),
  UNIQUE (IDSucursal)
);

CREATE TABLE CLIENTE(
  IDCliente INT NOT NULL AUTO_INCREMENT,
  IDClienteU INT NOT NULL,
  IDPersona INT NOT NULL,
  IDEmpresa INT NULL,
  IDFactura VARCHAR(200) NOT NULL,
  UNIQUE(IDFactura),
  UNIQUE(IDCliente)
);
# IDVendedor es el IDusuario
# desde la aplicacion se va enviar Fecha como la fecha del sistema
CREATE TABLE VENTA(
  IDVenta INT NOT NULL AUTO_INCREMENT,
  NumVenta INT NOT NULL,
  IDCliente INT NOT NULL,
  IDProducto INT NOT NULL,
  IDVendedor INT NOT NULL,
  Fecha DATE NOT NULL,
  UNIQUE(IDVenta)
);

CREATE TABLE PRODUCTO(
  IDProducto INT AUTO_INCREMENT,
  NombreProducto VARCHAR(100),
  IDProductoU VARCHAR(100) NOT NULL, ##ESTE ID ES PARA PODERLO MANEJAR CON EL Usuario
  IDTipoProducto INT NOT NULL,
  IDProveedor INT NOT NULL,
  IDCompra INT NOT NULL,
  IDVenta INT NULL,
  Cantidad INT,
  FechaCaducidad DATE NOT NULL,
  UNIQUE(IDProductoU),
  UNIQUE(IDProducto)
);
ALTER TABLE PRODUCTO ALTER Cantidad SET DEFAULT 0;

CREATE TABLE TIPOPRODUCTO(
  IDTipo INT NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(50),
  UNIQUE(IDTipo)
);

CREATE TABLE PRODUCTOXPROVEEDOR(
  IDProducto INT NOT NULL,
  IDProveedor INT NOT NULL,
  UNIQUE(IDProducto),
  UNIQUE(IDProveedor)
);

#Hay proveedores independientes?
CREATE TABLE PROVEEDOR(
  IDProveedor INT NOT NULL AUTO_INCREMENT,
  IDProveedorU VARCHAR(100) NOT NULL,
  IDEmpresa INT NULL,
  IDPersona INT NOT NULL,
  IDProducto INT NOT NULL,
  UNIQUE(IDProveedor)
);

CREATE TABLE VENTAXPRODUCTO(
  IDProducto INT NOT NULL,
  IDVenta INT NOT NULL,
  UNIQUE(IDProducto),
  UNIQUE(IDVenta)
);

CREATE TABLE COMPRAXPRODUCTO(
  IDProducto INT NOT NULL,
  IDCompra INT NOT NULL,
  UNIQUE(IDProducto),
  UNIQUE(IDCompra)
);

CREATE TABLE COMPRA(
  IDCompra INT NOT NULL AUTO_INCREMENT,
  IDCompraU VARCHAR(100) NOT NULL,
  IDUsuario INT NOT NULL,
  IDProducto INT NOT NULL,
  CantidadProducto INT NOT NULL,
  UNIQUE(IDCompra)
);
##CREATE TABLE INVENTARIO(
##  IDProductoI INT NOT NULL,
##  IDProducto INT NOT NULL,
##  Cantidad INT DEFAULT(0),
##  UNIQUE(IDProductoI)
##);
CREATE TABLE EMPRESA(
  IDEmpresa INT NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(50) NOT NULL,
  NIT CHAR (18) NOT NULL,
  Direccion VARCHAR(150)NULL,
  Telefono INT NOT NULL,
  NumeroContribuyente VARCHAR(150) NOT NULL, ##ID PARA EL USUARIO
  UNIQUE(Empresa),
  UNIQUE(NumeroContribuyente),
  UNIQUE(IDEmpresa)
);

##CREATE TABLE DEPARTAMENTO(
##  ID INT NOT NULL,
##  DepName VARCHAR(50) NOT NULL,
##  UNIQUE(ID)
##);

##CREATE TABLE MUNICIPIO(
##  ID INT NOT NULL,
##  MunName VARCHAR(50) NOT NULL,
##  DEPSV_ID INT NOT NULL,
##  UNIQUE(ID)
##);

##DECLARACION DE LLAVES PRIMARIAS
ALTER TABLE PERSONA ADD PRIMARY KEY (IDPersona);
ALTER TABLE TELEFONO ADD PRIMARY KEY (IDTelefono);
ALTER TABLE USUARIO ADD PRIMARY KEY (IDUsuario);
ALTER TABLE SUCURSAL ADD PRIMARY KEY (IDSucursal);
ALTER TABLE CLIENTE ADD PRIMARY KEY (IDCliente);
ALTER TABLE VENTA ADD PRIMARY KEY (IDVenta);
ALTER TABLE PRODUCTO ADD PRIMARY KEY (IDProducto);
ALTER TABLE TIPOPRODUCTO ADD PRIMARY KEY (IDTipo);
ALTER TABLE PRODUCTOXPROVEEDOR ADD PRIMARY KEY (IDProveedor, IDProducto);
ALTER TABLE PROVEEDOR ADD PRIMARY KEY (IDProveedor);
ALTER TABLE VENTAXPRODUCTO ADD PRIMARY KEY (IDProducto, IDVenta);
ALTER TABLE COMPRAXPRODUCTO ADD PRIMARY KEY (IDProducto, IDCompra);
ALTER TABLE COMPRA ADD PRIMARY KEY (IDCompra);
ALTER TABLE EMPRESA ADD PRIMARY KEY (IDEmpresa);
##ALTER TABLE DEPARTAMENTO ADD PRIMARY KEY (ID);
##ALTER TABLE MUNICIPIO ADD PRIMARY KEY (ID);

##llaves foraneas
##VENTAXPROCUCTO
ALTER TABLE VENTAXPRODUCTO ADD FOREIGN KEY (IDProducto) REFERENCES PRODUCTO(IDProducto);
ALTER TABLE VENTAXPRODUCTO ADD FOREIGN KEY (IDVenta) REFERENCES VENTA(IDVenta);

##PRODUCTOXPROVEEDR
ALTER TABLE PRODUCTOXPROVEEDOR ADD FOREIGN KEY (IDProducto) REFERENCES PRODUCTO(IDProducto);
ALTER TABLE PRODUCTOXPROVEEDOR ADD FOREIGN KEY (IDProveedor) REFERENCES PROVEEDOR(IDProveedor);

##COMPRAXPRODUCTO
ALTER TABLE COMPRAXPRODUCTO ADD FOREIGN KEY (IDCompra) REFERENCES COMPRA(IDCompra);
ALTER TABLE COMPRAXPRODUCTO ADD FOREIGN KEY (IDProducto) REFERENCES PRODUCTO(IDProducto);

##Persona
ALTER TABLE PERSONA ADD FOREIGN KEY (IDTelefono) REFERENCES TELEFONO(IDTelefono);

##Uuario
ALTER TABLE USUARIO ADD FOREIGN KEY (IDPersona) REFERENCES PERSONA(IDPersona);

##Sucursal
##ALTER TABLE SUCURSAL ADD FOREIGN KEY (IDMunicipio) REFERENCES MUNICIPIO(ID);

##Cliente
ALTER TABLE CLIENTE ADD FOREIGN KEY (IDPersona) REFERENCES PERSONA(IDPersona);

##Venta
ALTER TABLE VENTA ADD FOREIGN KEY (IDCliente) REFERENCES CLIENTE(IDCliente);
ALTER TABLE VENTA ADD FOREIGN KEY (IDVendedor) REFERENCES USUARIO(IDUsuario);


##Producto
ALTER TABLE PRODUCTO ADD FOREIGN KEY (IDTipoProducto) REFERENCES TIPOPRODUCTO(IDTipo);

##Proveedor
ALTER TABLE PROVEEDOR ADD FOREIGN KEY (IDEmpresa) REFERENCES EMPRESA(IDEmpresa);
ALTER TABLE PROVEEDOR ADD FOREIGN KEY (IDPersona) REFERENCES PERSONA(IDPersona);

##Compra
ALTER TABLE COMPRA ADD FOREIGN KEY (IDUsuario) REFERENCES USUARIO(IDUsuario);

##Empresa
##ALTER TABLE EMPRESA ADD FOREIGN KEY (IDMunicipio) REFERENCES MUNICIPIO(ID);
##ALTER TABLE EMPRESA ADD FOREIGN KEY (IDTelefono) REFERENCES TELEFONO(IDTelefono);
##Municipio
##ALTER TABLE MUNICIPIO ADD FOREIGN KEY (DEPSV_ID) REFERENCES DEPARTAMENTO(ID);
