/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuarios;

import cadillacs.racing.VentanaA;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author karic
 */
public class Usuarios extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
       
        this.setLocationRelativeTo(null);
        this.setSize(445,500);
        this.setTitle("Registro Usuario"); 
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbletiqueta = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblnickname = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtnickname = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnInicio = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbletiqueta.setBackground(new java.awt.Color(1, 50, 67));
        lbletiqueta.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbletiqueta.setForeground(new java.awt.Color(228, 241, 254));
        lbletiqueta.setText("Registro Usuario");
        getContentPane().add(lbletiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 300, 80));

        lblnombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(248, 148, 6));
        lblnombre.setText("Nombre:");
        getContentPane().add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        lblnickname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblnickname.setForeground(new java.awt.Color(248, 148, 6));
        lblnickname.setText("Nickname:");
        getContentPane().add(lblnickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lblpassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(248, 148, 6));
        lblpassword.setText("Password:");
        getContentPane().add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, -1));

        txtnombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(34, 49, 63));
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 180, 20));

        txtnickname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtnickname.setForeground(new java.awt.Color(34, 49, 63));
        getContentPane().add(txtnickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, 20));

        txtpassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(34, 49, 63));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 180, 20));

        btnInicio.setBackground(new java.awt.Color(1, 50, 67));
        btnInicio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 90, 30));

        btnAceptar.setBackground(new java.awt.Color(1, 50, 67));
        btnAceptar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 100, 30));

        lblfondo.setBackground(new java.awt.Color(228, 241, 254));
        lblfondo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblfondo.setForeground(new java.awt.Color(228, 241, 254));
        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuarios/logIn.jpg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 440, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String cadena2,cadena3,cadena4;      
        cadena2 = txtnombre.getText();    
        cadena3 = txtnickname.getText();
        cadena4 =  txtpassword.getText().toString();
        
        if (txtnombre.getText().equals("") || (txtnickname.getText().equals(""))
        || (txtpassword.getText().equals(""))) {
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            txtnombre.requestFocus();


    }//GEN-LAST:event_btnAceptarActionPerformed
        else {
        try {
           
            String url = "jdbc:mysql://localhost:3306/usuariosregistro";
            String usuario = "root";
            String contraseña = "chatamaria";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = (Connection) DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
                  stmt = (Statement) con.createStatement(); 
                  stmt.executeUpdate("INSERT INTO usuario VALUES('" + 0 + "','"+cadena2+"','"+cadena3+"','"+cadena4+"')");
                  System.out.println("Los valores han sido agregados a la base de datos ");
                 
                   
        } catch (InstantiationException ex) {
           Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
        }
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        this.txtnombre.setText("");    
        this.txtnickname.setText("");
        this.txtpassword.setText("");  
        

    }
    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char c = evt.getKeyChar();
        if((c < 'a'|| c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' '))evt.consume();
    }//GEN-LAST:event_txtnombreKeyTyped
    
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        VentanaA nextVA = new VentanaA();
        nextVA.setVisible(true);
        Usuarios.this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel lbletiqueta;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblnickname;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JTextField txtnickname;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
